- hosts: switches
  gather_facts: no
  collections:
    - cisco.ios
    - cisco.nxos


  tasks:
  - name: "Connectivity Check with Control machine by running ios commands"
    ios_command:
      commands:
        - show run | i hostname


  - name: "Configuring vlans in Cisco IOS switches"
    ios_vlans:
      config:
        - name: ios-vlan
          vlan_id: 200
          state: active
          shutdown: disabled
      state: merged
    when: ansible_network_os == ios

  - name: "Configureing vlans in Nexus switches"
    nxos_vlans:
      config:
        - vlan_id: 300
          name: nxos-vlan
          state: merged
      state: merged
    when: ansible_network_os == nxos
