- hosts: switches
  gather_facts: no
  collections:
    - cisco.ios
    - cisco.nxos


  tasks:
  - name: "Connectivity Check with Control machine by running ios commands"
    ios_command:
      commands:
        - show run | i hostname


  - name: "ios"
    ios_vlans:
      config:
        - name: ios-vlan
          vlan_id: 100
          state: active
          shutdown: disabled
      state: merged

  - name: "nexus"
    nxos_vlans:
      config:
        - vlan_id: 100
          name: nxos-vlan
          enabled: true
      state: merged
